### PR TITLE
Fix issue with create template (for #614)

### PR DESCRIPTION
**Pull request by dfalster**

### CODE REVIEW

**Review by ehwenk — COMMENTED** [review]
I've tests both long and wide datasets and both `metadata_create_template` and `metadata_add_traits` work with both formats. However, the default template now adds `population_id` and `individual_id` (& more) as fields, with default value `unknown`. This requires users to manually delete all columns for which they are not mapping on either a fixed value or column name, because otherwise `unknown` becomes the fixed values - i.e. all populations are assumed to be a single population with name "unknown", same for individuals, measurement_remarks, observation_number, method_number. Previously for the fields that are only used as needed, we'd simply omitted them from the default template.  Not sure if those fixes should be here, or as part of fixing entity_id

**Comment by dfalster** [comment]
Yes, I'll fix here. just tell em which ones to delete from the template

**Comment by ehwenk** [comment]
> Yes, I'll fix here. just tell em which ones to delete from the template

Remove these:

entity_id: unknown
population_id: unknown
individual_id: unknown
observation_id: unknown
observation_number: unknown
method_number: unknown
trait_name: trait
value: raw_trait_value
replicates: unknown
measurement_remarks: unknown

**Comment by dfalster** [comment]
For long datasets, we surely need `trait_name` and `value`?

**Comment by dfalster** [comment]
and perhaps makes sense to have replicates in there as unknown, until it's updated?

**Comment by ehwenk** [comment]
> and perhaps makes sense to have replicates in there as unknown, until it's updated?

But trait_name & value should only be in for long datasets - maybe they are, sorry... I copied the list from a newly produced "long" dataset.

Replicates could be in as a default "unknown", but it is also propagated within each trait entry, so it sort-of seems like clutter to have it appear twice. And it has to continue appearing under "traits" so that categorical traits can have it reset to ".na"

**Pull request merged**
