### PR TITLE
Reformat people names

### PR DESCRIPTION
**Pull request by GaryTruong**
Pull request for reformatting the people field in the metadata.yml files to address issue #215

### CODE REVIEW

**Review by ehwenk — COMMENTED** [review]
Question for @dfalster - Peter Clarke is still listed as a "data collector" but under institution is listed as "deceased". Other project-leads who are decreased have `affiliation: .na` or their final affiliation. What would our standard be? And one of the ideas of this restructure was that the information for the data collectors is ready to extract as authors of a future manuscript (or for other reasons). We should somehow identify "non-author" data collectors. Do you have any suggestions?

**Review by ehwenk — COMMENTED** [review]
While the terminology we're using is consistent with DataCite and our use of role with regard to our Zenodo release, I'm now worried about misinterpretations about `data_curator`. In terms of AusTraits and its release on Zenodo, AusTraits team members are clearly the curators  and people who hand us data are collectors . But of course a number of those collectors are also curators at a herbarium. So now I'm thinking maybe we should replace the term `data_curator` with `AusTraits_curator` for the AusTraits team member who has input the study. Then the herbarium curators (under `data_collectors` can be given an "additional_role" of `curator` (or `herbarium_curator` ??). What do you think @dfalster ?

**Comment by dfalster** [comment]
> Question for @dfalster - Peter Clarke is still listed as a "data collector" but under institution is listed as "deceased". Other project-leads who are decreased have `affiliation: .na` or their final affiliation. What would our standard be? And one of the ideas of this restructure was that the information for the data collectors is ready to extract as authors of a future manuscript (or for other reasons). We should somehow identify "non-author" data collectors. Do you have any suggestions?

Wow, that's a really hard one. Putting in affiliation doesn't seem right. We could have an optional notes field for authors, that only gets used occasionally?

**Comment by dfalster** [comment]
> While the terminology we're using is consistent with DataCite and our use of role with regard to our Zenodo release, I'm now worried about misinterpretations about `data_curator`. In terms of AusTraits and its release on Zenodo, AusTraits team members are clearly the curators and people who hand us data are collectors . But of course a number of those collectors are also curators at a herbarium. So now I'm thinking maybe we should replace the term `data_curator` with `AusTraits_curator` for the AusTraits team member who has input the study. 

Or curators or other databases. Sure, let's use something like  `AusTraits_curator` 

> Then the herbarium curators (under `data_collectors` can be given an "additional_role" of `curator` (or `herbarium_curator` ??). 

I'm not convinced this is necessary. Maybe easier to just have single role here as "collectors"?

**Comment by ehwenk** [comment]
> We could have an optional notes field for authors, that only gets used occasionally?

Yes. That is a good idea. So it won't be a default field created in new metadata files, but after `affiliation` there can be a `notes` column that can indicate `deceased` or `declines authorship` (if we want to document that). Then, `affiliation` can be an actual affiliation.

**Review by ehwenk — APPROVED** [review]
I've made my final changes to the branch and have carefully checked the AusTraits output table

**Review by dfalster — APPROVED** [review]
Great work team

**Comment by GaryTruong** [comment]
Closes Issue #215 

Align people with data cite people terms so that AusTraits people match the terms assigned in the Zenodo release

* Update formatting for people names in metadata
- people is now contributors, data_collectors, data_curator and assistants have been added as field under contributors
- modified metadata_create_template in setup.R to allow the new contributor fields to be created for new metadata templates
- data_collectors have names split into last_name and given_name, ORCID, affiliation and optional additional_role

* Updated ORCID and affiliations for all studies

Code used to update ORCID and affiliations in metadata.yml files

`dataset_id = file.path("data", list.files("data/"), "metadata.yml")

process_orcid <- function(data_collectors){
  if(any(!is.na(data_collectors))){
    author <- read_csv("author_list.csv", show_col_types = FALSE,
                       locale = readr::locale(encoding = "latin1")) %>%
      mutate(last_name = stringr::word(name, -1),
             given_name = stringr::word(name, 1)) %>%
      select(name, last_name, given_name, orcid, affiliation)

    collectors_tmp <- data_collectors %>% list_to_df() %>%
      mutate(given_name = stringr::word(given_name, 1)) %>%
      mutate(last_name = stringr::word(last_name, -1))

    author_tmp <- author %>%
      filter(last_name %in% collectors_tmp$last_name) %>%
      filter(given_name %in% collectors_tmp$given_name)

    out <- data_collectors

    for(i in seq_len(nrow(collectors_tmp))){

      out[[i]]$ORCID <- author_tmp$orcid[
        which(collectors_tmp$last_name[i] == author_tmp$last_name &
          collectors_tmp$given_name[i] == author_tmp$given_name)]

      out[[i]]$affiliation <- author_tmp$affiliation[
        which(collectors_tmp$last_name[i] == author_tmp$last_name &
          collectors_tmp$given_name[i] == author_tmp$given_name)]
      }

    out
  } else {
    return(NA_character_)
    }
  }

for(f in dataset_id){
  metadata <- read_metadata(f)
  metadata$contributors$data_collectors <- process_orcid(metadata$contributors$data_collectors)
  write_metadata(metadata, f)
}
`
* Change data_curators to austraits_curators

Co-authored-by: Elizabeth Wenk <ehwenk@gmail.com>
Co-authored-by: Daniel Falster <daniel.falster@unsw.edu.au>

**Pull request merged**
