### PR TITLE
Regenerate traits.yml from APD

### PR DESCRIPTION
**Pull request by ehwenk**
* regenerate traits.yml from APD version 1.0.0

### CODE REVIEW

**Comment by ehwenk** [comment]
@dfalster I've now updated traits.yml to match the APD v1.0.0

Where should we archive the script? It draws upon the 2 data files from APD repository (APD_traits.csv & APD_categorical_values.csv), then builds a file that goes into austraits.build repository.

Noting there are 2 manual tweaks required. 1) replacing ''' (3 single quotes) with ' (1 single quote) ; and 2) removing 3 instances of `allowed_values_levels: {}` that are inserted for the 3 categorical traits that don't have set values (fruiting_time, flowering_time, recruitment_time)

**Comment by dfalster** [comment]
Please add the code in a file within `scripts` and I'll review workflow from there

**Comment by dfalster** [comment]
@ehwenk I think can be merged now

**Review by dfalster — APPROVED** [review]

**Comment by dfalster** [comment]
Actually hold off for now. Just thought of one more change to make

**Pull request merged**
