### PR TITLE
Correcting minor errors in dataset metadata files

### PR DESCRIPTION
**Pull request by ehwenk**
Fixing minor errors in various metadata files, made over a several month period.

(A similar branch is likely to be reopened in the future, but I want this collection of fixes to be merged in.)

### CODE REVIEW

**Review by dfalster — CHANGES_REQUESTED** [review]
Hi Lizzy,

Is it necessary to change every row of ANB2019? this is a big file (15MB). I don't want to make this change lightly, as it adds 15MB to the Sie of the whole repo

Also, did you mean to change every row of Catford?

**Comment by dfalster** [comment]
Hi Lizzy, Well done with Catford and ANBG. Now only a few rows showing changes, as it should be. 

image


One more to check -- Ooi_2007 also has every row changed. Is that intended?

**Comment by ehwenk** [comment]
I'd like to leave Ooi approximately as I've done it - in this case there are 137 rows with modified data and I've annotated each of them with the "evidence". I am still planning on trying on redoing it so just these 137 lines appear as changes, but in this case there will be additional columns

**Comment by dfalster** [comment]
Ok, but if you add columns don't you change every row?

**Comment by dfalster** [comment]
Every row has changed, because the date format has changed. See

image

e.g. 2/02/79 changed to 2/2/1979

**Review by dfalster — APPROVED** [review]

**Comment by dfalster** [comment]
Nice work with Ooi_2007!!!

**Pull request merged**
