### PR TITLE
Fix replicate numbers that contain a range

### PR DESCRIPTION
**Pull request by GaryTruong**
Added code to `parse_data()` to override the replicate number range given in the metadata and instead use the actual replicate number.

A few other files in scripts have changes that weren't made by me. Something funny may have happened with the last merge into develop

### CODE REVIEW

**Comment by dfalster** [comment]
Thanks Gary, I'll let @ehwenk take a look and evaluate functionality. 

The extra files were that were removed off develop in https://github.com/traitecoevo/austraits.build/commit/d3ef658b74230e05b899b7787ff8fc197f752e77#diff-8c5967fd8486f34493710cc39b240aad46536cf4ee421ffd0479e6542db03e36. You seem to have added them back in here, so I've deleted again.

**Comment by GaryTruong** [comment]
These changes only affect the replicates that use a range i.e. contain a "-". It doesn't fix the replicates that contain a text description. @ehwenk Is there a specific reason why a text description was used rather than a numeric range?

**Comment by dfalster** [comment]
Hi @Gary, Looking more at you're code, I can't see how this aligns with the problem I thought you were solving. What is it that you've done here? 

Also, we don't want to simply remove anything with a range. so it's not clear how changing `5-20` to `5` changes anything. Can you explain?

As a side note, there's quite a big of reformatting that's also gone on here, e.g. at https://github.com/traitecoevo/austraits.build/pull/545/files#diff-f98c8b9285a838c8cc68409cf34244307af332673e82ebbee8c89c03e66fd47eL173

Presumably to make more readable, which is  overall  good thing?  The problem is that it makes it harder for anyone looking at the commit to see what's actually changed and relevant to this issues.  

So generally I'd suggest you don't reformat code in same commit, instead do this elsewhere in a tidy step, or at least in standalone commit on the same branch.

**Comment by ehwenk** [comment]
Changing Blackman_2010 from `5-10` to `5` was correcting a mistake I made inputting the data. There were 5 replicate individuals per site, each with 5-10 leaves sampled.

**Comment by GaryTruong** [comment]
In terms of the changed I have made, there are three steps. In the first step I wanted to take all the replicates within any study that contains a range using "-" to filter them out. In the second step I identified the actual replicate number by taking a count of the number of rows for a given species grouping by trait. The third step is adding the replicate numbers back into the main data.

The change in the Blackman_2020 metadata `5-20` to `5` is unrelated to the code I have written. The `5-20` in the Blackman study was incorrectly entered and the actual replicate is 5. 

My bad in terms of the reformatting. I was trying to tidy up the code and line it up to make it more readable. Ill make sure to include the changes either in a different step or separate commit.

**Comment by GaryTruong** [comment]
The changes were made based on Burrows_2001. Looking at the other studies that contain a range it doesnt look like it is applicable to them.

**Comment by dfalster** [comment]
Thanks for the explanation. Unfortunately this isn't the problem we were seeking to solve. The point of divergence may be what the term `replicates` means. Your explanation above suggests you're thinking that it's the number of records in AusTraits (for that study & trait) - is that right? This can of course be calculated from the data (as you have done), but it's not what we mean when we say replicates. Replicates was always meant to be the number off samples that were taken to get each record in AusTraits. This can't be calculated from the data, it's instead read from the paper or an additional column in the dataset. Is that right @ehwenk ?

**Comment by GaryTruong** [comment]
Yeah, there's definitely been some confusion regarding `replicates`. My solution works on studies that use raw_values for each row in their data (i.e. Burrows_2001). But it doesnt work when the values in the data are `individual means`, `site_means`, `multisite_means` etc. Some of the datasets provide the replicates for means in a separate column which I think is what Lizzy wants to use for the replicates. 

Going forward, replicates with a range are okay right? What we want is to use the actual replicates if available and if not available they remain as a range? If replicate values are derived from the methods and not contained within the data, it's not possible to get the actual replicate number? Is that correct?

**Comment by ehwenk** [comment]
Yes, sorry, what Issue #363 was meant to indicate was there are some studies where different rows of data have values that were generated from different numbers of replicate measurements. Replicates, per the AusTraits definitions: "Number of replicate measurements that comprise the data points for the trait for each measurement. A numeric value (or range) is ideal and appropriate if the value type is a `mean`, `median`, `min` or  `max`. For these value types, if replication is unknown the entry should be `unknown`. If the value type is `raw_value` the replicate value should be 1. If the value type is `expert_mean`, `expert_min`, or `expert_max` the replicate value should be `.na`."

Right now, AusTraits can only accept a single value per trait. For many studies (i.e. Lusk_2012, Catford_2014, etc) the range of replicates is given in the paper and we don't actually know on a row-by-row basis which rows of data have which replicate numbers. Then a range of values is as good as it gets. For other studies (ANBG_2019, Hayes_2012) there is a column (or multiple columns) in the data.csv file that specifies the replicates for each row of data. In these cases, the information in that row should be read in, rather than putting in a range. For those studies with complex strings of information, those are generally notes that either need to stay or can be translated to a column of "replicate values" once this functionality exists.

**Comment by GaryTruong** [comment]
Closing pull request and making further changes on a different branch

**Pull request closed without merging**
