### PR TITLE
Update test-pre_process.R

### PR DESCRIPTION
**Pull request by GaryTruong**
Open pull request to see the test coverage percentage on this branch

### CODE REVIEW

**Comment by dfalster** [comment]
Hi @GaryTruong Can you update so tests are passing and then I'll review?

**Comment by GaryTruong** [comment]
> Hi @GaryTruong Can you update so tests are passing and then I'll review?

Build is failing with test-constancy.R, there have been changes that don't match the comparison set. Is the fix here to update the comparison set rds?

**Comment by dfalster** [comment]
Merging this was more complicated than hoped. There were changes on develop, which weren't working with the tests on this branch. 

Also, for now I've disabled all tests related to build_process, as remake will  doesn't currently work in subdirectory

**Comment by GaryTruong** [comment]
> Hi @GaryTruong - can you please merge PR into develop, using a squash commit?

Done

**Pull request merged**
